#! /bin/sh
#
# This script invokes Jython for translating a FASTA file
# using the Biojava3 implementation
#
# Usage:
#
#   ./DNAtranslate file.fa [n]
#
# Example
#
#   ./DNAtranslate ../../../test/data/test-dna.fa
#
# Dependencies: scala jre 
# Included:     bioscala biojava3
#   

# /usr/share/java/jboss-profiler.jar

src=`dirname $0`
javaopts="-Xmx128M -Xms16M -Xss16M"
export CLASSPATH=../scala/lib/biojava/biojava3-core-3.0-SNAPSHOT.jar
# env JAVA_OPTS="$javaopts" jython DNAtranslate.jpy $*

env JYTHONPATH=$src/lib/biojava3-core-3.0-alpha1.jar jython DNATranslate.py $* 
# env JYTHONPATH=$src/lib/biojava3-core-3.0-latest.jar jython DNATranslate.py $* 
